# 🚀 Enhanced Nanpin Bot Configuration
# Integrated with ALL API services from backpack_gemini_ai_v1.3 system
# Comprehensive data sources for maximum trading intelligence

# Core Trading Configuration
trading:
  enable_real_trading: true
  max_daily_loss: 0.05          # 5% circuit breaker
  min_confidence_threshold: 0.55 # Require 55% confidence for trades (backtest optimized)
  max_position_size: 0.15       # 15% max portfolio per position
  primary_symbol: "BTC_USDC_PERP"  # BTC Perpetual Futures
  nanpin_scaling_factor: 1.618  # Golden ratio scaling
  max_nanpin_levels: 8          # Maximum DCA levels
  base_position_size: 100       # Base USDC amount per level

# API Configuration - All Services from v1.3
api:
  # Primary Exchange
  backpack:
    base_url: "https://api.backpack.exchange"
    key: ${BACKPACK_API_KEY}
    secret: ${BACKPACK_SECRET_KEY}
    testnet: false
    live_trading: true
    rate_limits:
      requests_per_second: 100
      orders_per_second: 20
      
  # Market Data APIs
  binance:
    api_key: ${BINANCE_API_KEY}
    secret_key: ${BINANCE_SECRET_KEY}
    enabled: true
    
  # Liquidation Intelligence
  coinglass:
    api_key: ${COINGLASS_API_KEY}
    enabled: true
    endpoints:
      liquidation_map: "https://open-api-v4.coinglass.com/api/futures/liquidation_map"
      funding_rates: "https://open-api-v4.coinglass.com/api/futures/funding_rate"
      
  # On-chain Analytics
  flipside:
    api_key: ${FLIPSIDE_API_KEY}
    mcp_url: ${FLIPSIDE_MCP_URL}
    enabled: true
    
  # Institutional Analytics
  octagon:
    api_key: ${OCTAGON_API_KEY}
    enabled: true
    
  # Economic Data
  fred:
    api_key: ${FRED_API_KEY}
    enabled: true
    indicators:
      - fed_funds_rate
      - inflation_rate_yoy
      - vix
      - yield_10y
      - dollar_index
      
  # DeFi Analytics
  sosovalue:
    api_key: ${SOSOVALUE_API_KEY}
    enabled: true
    
  # AI Optimization
  gemini_ai:
    api_key: ${GEMINI_API_KEY}
    model_name: "gemini-2.5-flash"
    temperature: 0.25
    max_tokens: 4096
    enabled: true

# Enhanced Nanpin Strategy Configuration
nanpin_strategy:
  # Core Parameters
  base_investment: 100          # USDC per initial position
  scaling_multiplier: 1.5       # Position size multiplier per level
  price_drop_threshold: 0.03    # 3% drop triggers next level
  take_profit_percentage: 0.08  # 8% take profit target
  max_drawdown_stop: 0.15       # 15% max drawdown stop loss
  
  # Fibonacci-based Levels (Enhanced Configuration)
  fibonacci_levels:
    '23.6%':
      ratio: 0.236
      base_multiplier: 2
      confidence: 0.7
    '38.2%':
      ratio: 0.382
      base_multiplier: 3
      confidence: 0.8
    '50.0%':
      ratio: 0.500
      base_multiplier: 5
      confidence: 0.85
    '61.8%':
      ratio: 0.618
      base_multiplier: 8
      confidence: 0.9
    '78.6%':
      ratio: 0.786
      base_multiplier: 13
      confidence: 0.95
      
  # Entry windows (distance from Fibonacci level)
  entry_windows:
    '23.6%': [-3.0, -0.5]   # 0.5% to 3% below
    '38.2%': [-5.0, -1.0]   # 1% to 5% below  
    '50.0%': [-7.0, -1.5]   # 1.5% to 7% below
    '61.8%': [-10.0, -2.0]  # 2% to 10% below
    '78.6%': [-15.0, -3.0]  # 3% to 15% below
    
  # Dynamic leverage scaling
  base_leverage: 3.0
  max_leverage: 18.0
  drawdown_multiplier: 0.6
  fear_multiplier: 0.4
  
  # Entry criteria
  min_drawdown: -18        # -18% drawdown threshold
  max_fear_greed: 35       # Fear & Greed ≤35
  min_days_since_ath: 7    # At least 7 days from ATH
  
  # Timing
  cooldown_hours: 48
  dynamic_cooldown: true
  
  # Update frequencies (seconds) - REQUIRED for enhanced strategy
  update_frequencies:
    macro_analysis: 1800      # 30 minutes
    liquidation_intel: 300    # 5 minutes  
    flipside_metrics: 3600    # 1 hour
    price_validation: 60      # 1 minute
    
  # API Rate Limiting - Optimized to 95% of limits
  api_rate_limits:
    # CoinGecko Pro: 500 calls/min → 475 calls/min (95%)
    coingecko:
      calls_per_minute: 475
      calls_per_second: 7.9     # 475/60 = 7.9
      burst_limit: 10           # Allow small bursts
      cooldown_on_429: 65       # 65 second cooldown on rate limit
      
    # CoinMarketCap Basic: 333 calls/min → 316 calls/min (95%)  
    coinmarketcap:
      calls_per_minute: 316
      calls_per_second: 5.3     # 316/60 = 5.3
      burst_limit: 8            # Allow small bursts
      cooldown_on_429: 65       # 65 second cooldown on rate limit
      
    # CoinGlass: 1000 calls/day → 950 calls/day (95%)
    coinglass:
      calls_per_day: 950
      calls_per_hour: 39        # 950/24 = 39.6
      calls_per_minute: 0.65    # Conservative spacing
      cooldown_on_429: 300      # 5 minute cooldown
      
    # Binance: 1200 weight/min → 1140 weight/min (95%)
    binance:
      weight_per_minute: 1140
      calls_per_second: 10      # Conservative estimate
      burst_limit: 15           # Allow bursts
      cooldown_on_429: 65       # 65 second cooldown
      
    # FRED: 120 calls/day → 114 calls/day (95%)
    fred:
      calls_per_day: 114
      calls_per_hour: 4.75      # 114/24 = 4.75
      calls_per_minute: 0.08    # Very conservative
      cooldown_on_429: 3600     # 1 hour cooldown
      
  # Smart Request Management
  request_optimization:
    batch_requests: true        # Batch compatible requests
    intelligent_spacing: true   # Space requests optimally
    adaptive_throttling: true   # Slow down on approaching limits
    priority_queuing: true      # Prioritize critical requests
  
  # Dynamic Position Sizing - Automatically adjusts based on collateral
  dynamic_position_sizing:
    enabled: true               # Enable dynamic sizing
    update_frequency: 3600      # Update every hour (seconds)
    min_balance_threshold: 50   # Minimum $50 to trade
    
    # Kelly Criterion Parameters
    kelly_fraction: 0.25        # Use 25% of Kelly (conservative)
    min_position_pct: 0.02      # 2% minimum position size
    max_position_pct: 0.15      # 15% maximum position size
    
    # Leverage Optimization
    leverage_optimization:
      enabled: true
      balance_brackets:
        small: {max: 200, leverage: 8}    # <$200: 8x leverage
        medium: {max: 1000, leverage: 5}  # $200-1k: 5x leverage  
        large: {max: 5000, leverage: 3}   # $1k-5k: 3x leverage
        xlarge: {leverage: 2}             # >$5k: 2x leverage
    
    # Risk Management
    max_capital_usage: 0.80     # Use max 80% of capital
    emergency_buffer: 0.20      # Keep 20% emergency buffer
    volatility_adjustment: true # Adjust for market volatility
    
  # Static Position Sizing (fallback if dynamic disabled)
  base_position_pct: 0.2   # 20% of remaining capital
  max_single_position: 12000  # $12K max single position
  min_remaining_capital: 500  # $500 minimum remaining
    
  # Dynamic Sizing with Kelly Criterion
  kelly_criterion:
    enabled: true
    fraction: 0.25              # Conservative Kelly fraction
    max_position: 0.20          # 20% max position size
    lookback_period: 50         # Days for Kelly calculation
    
  # Market Regime Detection
  regime_detection:
    enabled: true
    volatility_threshold: 0.02  # 2% daily volatility threshold
    trend_lookback: 20          # Days for trend analysis
    use_garch_forecasting: true # Use GARCH for volatility prediction

# Comprehensive Market Intelligence
market_intelligence:
  # Multi-Factor Analysis (from v1.3)
  multi_factor_analysis:
    enabled: true
    update_interval: 300        # 5 minutes
    
    # Factor Weights
    factor_weights:
      technical: 0.25           # Technical indicators
      onchain: 0.30             # On-chain metrics (high weight due to Flipside)
      macro: 0.25               # Economic indicators (FRED data)
      sentiment: 0.15           # Market sentiment
      temporal: 0.05            # Time-based factors
      
    # Execution Requirements
    execution_requirements:
      factor_requirement: "TWO_NON_TECHNICAL"
      min_confidence: 0.65
      min_non_technical_factors: 2
      
  # Liquidation Intelligence (CoinGlass) - Enhanced Configuration
  liquidation_analysis:
    enabled: true
    update_interval: 60         # 1 minute
    min_liquidation_volume: 50000  # $50k minimum volume
    confidence_threshold: 0.75
    
    # Threshold settings for liquidation aggregator
    thresholds:
      min_liquidation_volume: 100000  # $100K minimum
      cluster_distance_pct: 2.0       # 2% price clustering
      significance_threshold: 0.05     # 5% of total OI
      
    # Retry configuration
    retry:
      max_retries: 3
      retry_delay: 1.0
      
    # Timeout settings
    timeouts:
      request_timeout: 10
      total_timeout: 30
    
  # Volatility Forecasting (GARCH)
  garch_forecasting:
    enabled: true
    model_type: "GARCH"
    p: 1
    q: 1
    forecast_horizon: 24        # Hours
    min_observations: 100
    
  # Economic Intelligence (FRED)
  economic_intelligence:
    enabled: true
    update_interval: 3600       # 1 hour
    correlation_threshold: 0.3  # Minimum correlation to consider

# Risk Management (Enhanced from v1.3)
risk_management:
  # Portfolio Limits
  portfolio_limits:
    max_total_exposure: 0.85    # 85% max portfolio exposure
    max_single_position: 0.20   # 20% max per position
    max_correlation_exposure: 0.60  # Max correlated exposure
    
  # Dynamic Risk Adjustment
  dynamic_risk:
    enabled: true
    volatility_adjustment: true
    regime_adjustment: true
    correlation_adjustment: true
    
  # Emergency Controls
  emergency_controls:
    max_daily_loss: 0.05        # 5% max daily loss
    margin_call_threshold: 0.15 # 15% margin threshold
    auto_reduce_exposure: true  # Auto-reduce on high volatility

# AI Enhancement (Gemini Integration)
ai_enhancement:
  enabled: true
  optimization_interval: 1800   # 30 minutes
  confidence_threshold: 0.70
  
  # Feature Enhancements
  feature_enhancements:
    nanpin_optimization: true   # AI-optimized scaling levels
    regime_detection: true      # AI-enhanced market regime detection
    risk_optimization: true     # AI-optimized risk parameters
    entry_timing: true          # AI-optimized entry timing
    
  # Cross-feature Coordination
  coordination:
    conflict_resolution: true
    synergy_identification: true
    regime_coordination: true

# Performance Monitoring
performance_monitoring:
  enabled: true
  real_time_metrics:
    - pnl_tracking
    - position_sizing
    - market_regime
    - volatility_forecast
    - liquidation_levels
    - economic_indicators
    - ai_confidence
    - nanpin_efficiency
    
  reporting:
    real_time_dashboard: true
    hourly_summaries: true
    daily_reports: true
    performance_attribution: true

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/enhanced_nanpin.log"
  max_size: 100MB
  backup_count: 10
  feature_specific_logging:
    nanpin_strategy: true
    market_intelligence: true
    risk_management: true
    ai_enhancement: true
    api_interactions: true

# Performance Targets
performance_targets:
  # Trading Targets
  daily_return: 0.015           # 1.5% daily target
  monthly_return: 0.45          # 45% monthly target
  win_rate_target: 0.75         # 75% win rate
  
  # Risk Targets
  max_drawdown: 0.08            # 8% max drawdown
  sharpe_ratio_target: 3.0      # 3.0 Sharpe ratio
  
  # Nanpin Specific
  avg_scaling_levels: 3.5       # Average levels per trade
  scaling_efficiency: 0.85      # 85% scaling efficiency
  
  # AI Enhancement
  ai_optimization_success: 0.80 # 80% AI optimization success
  regime_detection_accuracy: 0.75 # 75% regime accuracy